// Executes production AS2 methods. Does not qualify native registration,
// Skyrim scene ownership, camera behavior or headset comfort.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../tools/vr-racesex-patches/Appearance.as.inc'),'utf8');
const prototype=Function('return ({'+source.replace(/^   function (\w+)\(/gm,'$1(').replace(/^   }[ \t]*$/gm,'},')+'})')();
global.RaceMenuDefines={ENTRY_TYPE_CAT:1,ENTRY_TYPE_SLIDER:2};
const calls=[];
let revision=1;
let sections=[{provider:'test.mod',id:'shape',label:'Shape',flag:1<<20,order:42,controls:[{id:'width',label:'Width',minimum:0,maximum:1,step:.1,value:.5}]}];
const api={GetMenuExtensionsRevision:()=>revision,GetMenuExtensions:()=>sections,GetMenuCategoryPresentation:()=>({label:'',visible:-9999,order:-9999,controlIds:''}),SetMenuExtensionValue:(...args)=>calls.push(args)};
global._global={skse:{plugins:{CharGen:api}}};
const o=Object.assign({},prototype,{bMenuInitialized:true,categoryList:{entryList:[{flag:2044}],requestInvalidate(){this.invalidated=true;}},itemList:{entryList:[],requestInvalidate(){this.invalidated=true;}}});
o.RefreshVRMenuExtensions();
assert.equal(o.categoryList.entryList.length,2);
assert.equal(o.itemList.entryList.length,1);
const entry=o.itemList.entryList[0];
assert.equal(entry.callbackName,'');
entry.internalCallback.call({entryObject:entry,position:.7});
assert.deepEqual(calls,[['test.mod','width',.7]]);
o.RefreshVRMenuExtensions();assert.equal(o.itemList.entryList[0],entry,'unchanged registry does not churn renderers');
o.itemList.entryList=[];o.RefreshVRMenuExtensions();assert.equal(o.itemList.entryList.length,1,'race/sex rebuild repopulates controls');
o.categoryList.entryList=[{flag:2044},{flag:1<<20}];o.RefreshVRMenuExtensions();
assert.equal(o.itemList.entryList.length,0,'legacy flag conflicts do not overwrite controls');
assert.match(o.vrExtensionFault,/conflict/);
sections=[];revision++;o.RefreshVRMenuExtensions();assert.equal(o.itemList.entryList.length,0);
// Move registered clips, wrap action buttons, resize the list through its
// listHeight contract (never its MovieClip _height / slider geometry).
const filter={_width:150},name={_width:150};
const layout=Object.assign({},prototype,{vrMenuProfile:{consolidate:1},vrFilterButton:filter,vrNameButton:name,ITEMLIST_HEIGHT_FULL:825,ITEMLIST_HEIGHT_SHARED:639,BOTTOMBAR_SHOWN_Y:949,raceDescription:{_visible:false},racePanel:{ListBackground:{getBounds:()=>({xMin:0,xMax:430,yMin:0,yMax:1024})},slidingCategoryList:{_y:40},categoryButtons:{_y:40}},searchWidget:{_y:10},itemList:{_y:100,listHeight:825,_height:999},bottomBar:{_x:0,_y:949,background:{_visible:true},playerInfo:{_x:900,_y:0,PlayerRace:{_x:70}}},modeSelect:{_x:1000,_y:0,_width:200,_xscale:100,_yscale:100,getBounds(){return {xMin:this._x-this._width,xMax:this._x,yMin:this._y,yMax:this._y+20};}},navPanel:{buttons:[{_width:100},{_width:100},{_width:100},name,filter]}});
layout.racePanel.ListBackground._y=0;layout.racePanel.ListBackground._height=1024;
const patchSource=fs.readFileSync(require('node:path').join(__dirname,'../tools/patch-vr-racesex-swf.ps1'),'utf8');
assert.match(patchSource,/categoryDivider\.ParentNode\.RemoveChild\(\$categoryDivider\)/,'remove non-addressable double-rule shape at build time');
const makeField=size=>({format:{size},future:{size},getTextFormat(){return {...this.format};},getNewTextFormat(){return {...this.future};},setTextFormat(f){this.format={...f};},setNewTextFormat(f){this.future={...f};}});
layout.bottomBar.playerInfo.PlayerRace=Object.assign(makeField(24),{_x:70,_y:2});
layout.navPanel._x=148;layout.navPanel._y=15;
for(const button of layout.navPanel.buttons) {button.textField=makeField(20);button.label='Action';button._visible=true;}
const inactive={_width:900,_visible:false,label:'',textField:makeField(20)};layout.navPanel.buttons.push(inactive);
layout.bottomBar.playerInfo.RaceLabel={_x:4,_visible:true};
layout.LayoutVRPanel();assert.equal(layout.itemList.listHeight,650);assert.equal(layout.itemList._height,999);
assert.equal(layout.bottomBar.playerInfo.RaceLabel._visible,false);
assert.equal(layout.bottomBar.playerInfo.PlayerRace._x,0,'race name needs no prefix or its reserved gap');
assert.equal(name._y,40);assert.equal(layout.bottomBar.background._visible,false);
assert.equal(layout.navPanel._x,12,'action panel has real left padding, not stock imported offset');
assert.equal(layout.bottomBar.playerInfo._y,92,'race follows last action row with padding');
assert.equal(layout.bottomBar.playerInfo.PlayerRace.format.size,25);
assert.equal(name.textField.format.size,25);assert.equal(name.textField.future.size,25);
assert.equal(filter.textField.format.size,20,'Filter is not a footer action');
assert.equal(inactive.textField.format.size,20,'unused slots do not consume rows');
assert.equal(layout.racePanel.ListBackground._y,70,'tabs occupy a separate strip above background');
assert.equal(layout.bottomBar._y,864,'larger actions have a reserved lower area');
assert.equal(layout.modeSelect.getBounds().xMin,8,'right-anchored tab container is accounted for');
layout.LayoutVRPanel();assert.equal(layout.searchWidget._y,85,'repeated layout is idempotent');
const conditional={_width:260,_visible:true,label:'Choose Texture',textField:makeField(20)};
layout.navPanel.buttons.push(conditional);layout.LayoutVRPanel();
assert.equal(conditional._y,80,'conditional actions wrap after current live widths');
assert.equal(layout.bottomBar.playerInfo._y,132);
assert.equal(layout.bottomBar._y,844,'third action row grows footer instead of pinning race to edge');
assert.equal(layout.itemList.listHeight,630);
conditional._visible=false;layout.LayoutVRPanel();assert.equal(layout.itemList.listHeight,650,'removing contextual action restores list space');
assert.equal(layout.bottomBar._y,864,'layout growth is idempotent and reversible');
layout.vrMenuProfile={consolidate:0};layout.LayoutVRPanel();
assert.equal(layout.itemList.listHeight,825);assert.equal(layout.bottomBar.background._visible,true);assert.equal(layout.searchWidget._y,10);
assert.equal(layout.racePanel.ListBackground._height,1024);
assert.equal(layout.bottomBar.playerInfo.RaceLabel._visible,true);
assert.equal(layout.bottomBar.playerInfo.PlayerRace._x,70);
assert.equal(layout.bottomBar.playerInfo.PlayerRace._y,2);
assert.equal(layout.navPanel._x,148);assert.equal(layout.navPanel._y,15);
assert.equal(name.textField.format.size,20);assert.equal(name.textField.future.size,20);
assert.equal(layout.bottomBar.playerInfo.PlayerRace.format.size,24);
global.Stage={visibleRect:{x:0,y:0,width:1024,height:1024}};
let view=0,state=0;
const placements=[];api.SetMenuPolarPlacement=(...args)=>{placements.push(args);state=0;return true;};
api.GetMenuView=()=>view;api.GetMenuPolarPlacementState=()=>state;
const polar=Object.assign({},prototype,{vrMenuProfile:{azimuth:25,elevation:5,distance:90,surfaceScale:110,pickerAzimuth:40,pickerElevation:0,pickerDistance:80,pickerSurfaceScale:100},racePanel:{ListBackground:{getBounds:()=>({xMin:0,xMax:430,yMin:70,yMax:1024})}},colorField:{_visible:false,getBounds:()=>({xMin:20,xMax:500,yMin:300,yMax:600})},localToGlobal:p=>{p.x+=10;}});
polar.vertexEditor={enabled:false};
polar.UpdateVRWorldPlacement();assert.deepEqual(placements.pop(),[25,5,90,110,225,547]);
state=1;polar.UpdateVRWorldPlacement();assert.equal(placements.length,0,'steady-state poll does not move menu');
polar.localToGlobal=p=>{p.x+=50;};
polar.UpdateVRWorldPlacement();assert.equal(placements.length,0,'dynamic movie geometry does not recenter surface');
api.menuProfiles={'VR Normal':polar.vrMenuProfile,'VR Face':{azimuth:70,distance:250}};
polar.vrMenuProfile=api.menuProfiles['VR Face'];view=1;
polar.UpdateVRWorldPlacement();assert.deepEqual(placements.pop(),[25,5,90,110,265,547],'view transition uses shared normal placement');
state=1;polar.UpdateVRWorldPlacement();assert.equal(placements.length,0,'face steady-state poll does not move menu');
polar.localToGlobal=p=>{p.x+=10;};
polar.colorField._visible=true;polar.UpdateVRWorldPlacement();assert.deepEqual(placements.pop(),[40,0,80,100,270,450]);
state=1;polar.UpdateVRWorldPlacement();assert.equal(placements.length,0,'steady modal does not chase viewer');
polar.colorField._visible=false;polar.UpdateVRWorldPlacement();assert.deepEqual(placements.pop(),[25,5,90,110,225,547],'modal close restores main placement');
state=1;view=0;polar.UpdateVRWorldPlacement();assert.deepEqual(placements.pop(),[25,5,90,110,225,547],'return to normal reanchors once');
state=0;polar.UpdateVRWorldPlacement();assert.equal(placements.length,1,'not-yet-ready native surface permits retry');
placements.length=0;state=2;polar.UpdateVRWorldPlacement();assert.equal(placements.length,0,'unavailable native surface does not retry forever');
polar.vertexEditor={enabled:true,vrLargeCanvas:false,vrWorkspaceBounds:{xMin:16,xMax:912,yMin:90,yMax:900},localToGlobal:p=>{p.x+=20;}};
polar.UpdateVRWorldPlacement();assert.deepEqual(placements.pop(),[48,5,90,110,484,495],'Sculpt default has independent leftward angle');
state=1;polar.UpdateVRWorldPlacement();assert.equal(placements.length,0,'steady Sculpt does not chase viewer');
api.menuProfiles['VR Normal'].sculptAzimuth=60;polar.UpdateVRWorldPlacement();assert.equal(placements.pop()[0],60,'Sculpt angle override');
polar.colorField._visible=true;polar.UpdateVRWorldPlacement();assert.equal(placements.pop()[0],40,'picker remains independent while Sculpt open');
polar.colorField._visible=false;polar.vertexEditor.enabled=false;polar.UpdateVRWorldPlacement();assert.equal(placements.pop()[0],25,'exit Sculpt restores ordinary main angle');
console.log('Wishlist adapter: stable extension controls, rebuilds, collision rejection, registered-clip layout and list sizing passed (surrogate only).');
